name: Pytest summary
description: Run tests using pytest and display summary
author: Dario Curreri

branding:
  icon: check-square
  color: gray-dark

inputs:
  paths:
    description: The path to the folder containing the tests
    required: false
    default: tests
  options:
    description: The pytest options
    required: false
  output:
    description: The path to the output file to create
    required: false
  show:
    description: Which tests have to be shown in the summary
    required: false

runs:
  using: composite
  steps:

    - run: pip install pytest
      shell: bash

    - run: pytest ${{ inputs.options }} --junit-xml=.test_report.xml ${{ inputs.paths }}
      shell: bash

    - uses: test-summary/action@v1
      with:
        paths: .test_report.xml
        output: ${{ inputs.output }} 
        show: ${{ inputs.show }} 
      if: always()