name: "[TEST] with output"

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          output: test-summary.md

      - name: Check report
        run: python -c "import os; assert 'test-summary.md' in os.listdir('.')"
        if: always()