name: "[TEST] with paths"

on:
  workflow_dispatch:

jobs:
  single-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          paths: tests/test_true.py
  multiple-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          paths: |
            tests/test_false.py
            tests/test_true.py
  glob-pattern:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          paths: tests/**.py