name: "[TEST] simple"

on:
  workflow_dispatch:

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Run tests
        uses: dariocurr/pytest-summary@main