name: "Validate action"

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          paths: tests/test_true.py
          options: -x
          show: all